# This file is machine-generated - editing it directly is not advised

[[AbbreviatedTypes]]
deps = ["Reexport", "StaticArrays"]
git-tree-sha1 = "2195e9e3530c40f80f4f0426d8a240b198262173"
repo-rev = "main"
repo-url = "https://github.com/wsshin/AbbreviatedTypes.jl"
uuid = "1766def0-c946-4dda-a59e-d0d07f8410f7"
version = "0.1.0"

[[GeometryPrimitives]]
deps = ["LinearAlgebra", "StaticArrays", "Statistics"]
git-tree-sha1 = "29153406eb3a97284bc9209b8bb84b1627decc15"
repo-rev = "master"
repo-url = "https://github.com/stevengj/GeometryPrimitives.jl"
uuid = "17051e67-205e-509e-8301-03b320b998e6"
version = "0.1.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "57d8440b0c7d98fc4f889e478e80f268d534c9d5"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.0.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaggeredGridCalculus]]
deps = ["AbbreviatedTypes", "LinearAlgebra", "Reexport", "SparseArrays", "StaticArrays"]
git-tree-sha1 = "bce8614dad2f24eab4f2d69681375b39f988bacf"
repo-rev = "main"
repo-url = "https://github.com/wsshin/StaggeredGridCalculus.jl"
uuid = "fead5d43-7759-5ac8-9dff-97135399d9eb"
version = "0.1.0"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "2f01a51c23eed210ff4a1be102c4cc8236b66e5b"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.1.0"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
